### ISSUE TITLE
Initial window size  is too small

### ISSUE THREAD

**Issue by mfederczuk** [RiedleroD/pymark#1]
The initial launch size of the window is too small to properly see the results of the benchmark.  
The window is still resizable and can still be maximized, though.

Operating System: Ubuntu Desktop 20.10 x86_64
Desktop Environment: GNOME 3.38.2

![image](https://user-images.githubusercontent.com/14075939/113425993-16830580-93d3-11eb-8636-e11a39fe0190.png)

**Comment by RiedleroD** [comment]
fixed in 6c5a1b2 - waiting for approval from @mfederczuk

**Comment by mfederczuk** [comment]
Looks better, but pretty much all of the expression labels are still cut off.

![image](https://user-images.githubusercontent.com/14075939/113430286-2d792600-93da-11eb-8e61-1631aad86cdc.png)

**Comment by RiedleroD** [comment]
ok, 5bfcb17 should fix this. Please confirm, @mfederczuk.

**Comment by mfederczuk** [comment]
Now it's looking good 👍🏻
